files:
  - source: /Translations/English (default)/
    translation: '%original_path%/%two_letters_code%/%original_file_name%'
  - source: '*english.vdf'
    translation: '%original_path%/700330_loc_%language%.vdf'
